# .github/workflows/docker-publish.yml

name: Docker Image Build and Publish to GHCR

on:
  push:
    # Trigger the workflow when changes are pushed to the 'main' branch
    branches: [ "main" ]
  
# Give the workflow read and write permissions to packages
permissions:
  contents: read
  packages: write

jobs:
  build-and-push-ghcr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (A feature to build images more efficiently)
        uses: docker/setup-buildx-action@v3

      # 1. Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # Use the secret we created earlier for authentication
          password: ${{ secrets.CR_PAT }}

      # 2. Define Image Name and Tag
      - name: Define Image Tag
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=sha,format=short

      # 3. Build and Push the Docker Image
      - name: Build and push Docker image
        uses: docker/build-and-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}